### ISSUE TITLE
The value of the exit state at 0.2.18. tar. gz 'is not 0

### ISSUE THREAD

**Issue by rain242** [smorabit/scWGCNA#116] opened 2023-05-21 03:44 UTC
**Describe the bug**
Install package 'C:/Users/mac/AppData/Local/temp/RtmpmKBjj0/file11f846e3b34/hdWGCNA'_ The value of the exit state at 0.2.18. tar. gz 'is not 0

**Steps to reproduce**

# install BiocManager
install.packages("BiocManager")

# install Bioconductor core packages
BiocManager::install()

# install additional packages:
install.packages(c("Seurat", "WGCNA", "igraph", "devtools"))

devtools::install_github('smorabit/hdWGCNA', ref='dev')

```
# Put code in this box
```

**R session info**
Please run `sessionInfo()` and report the output.

**Screenshots**

**More than one problem?** 
If you have more than one problem with hdWGCNA, create separate issues for your individual problems.

**Comment by smorabit** [comment] 2023-05-21 19:39
Unfortunately I am not able to reproduce this error on my computer. I am wondering if you are using a Windows computer? Personally I only have access to Mac and Linux operating systems, so hdWGCNA has only ever been tested on those systems and I cannot offer any advice for Windows users at this time.

**Comment by smorabit** [comment] 2023-06-02 17:46
Closing this issue for now but feel free to re-open if you have new information.

**Closed as completed by smorabit** 2023-06-02 17:46 UTC
