### ISSUE TITLE
MetacellsByGroups function error

### ISSUE THREAD

**Issue by dhivyaa-6** [smorabit/scWGCNA#51] opened 2022-09-05 21:09 UTC
Thanks for the hdWGCNA package, it will be helpful for our spatial analyses. 

I was trying to use the MetacellsByGroups function and run into an error, I tried different parameters for k, max-shared, and min-cells. 

       seurat_obj <- SetupForWGCNA(
      seurat_obj,
      gene_select = "variable",
      wgcna_name = "ImageA" # the name of the hdWGCNA experiment
       )   

      a <- c(25, 1, 2)
      seurat_obj <- MetacellsByGroups(seurat_obj,
      group.by = "cell_type", 
      k = a[1], 
      max_shared = a[2],
      min_cells = a[3], 
      ident.group = "cell_type", # set the Idents of the metacell seurat object
      assay = 'RNA',reduction = "pca",
      slot = 'scale.data',
     verbose = T)

Error message pasted below:

Overlap QC metrics:
Cells per bin: 8
Maximum shared cells bin-bin: 2
Mean shared cells bin-bin: 0.610615079365079
Median shared cells bin-bin: 1
Error in if (sparse && !sM) data <- as(data, "sparseMatrix") else if (!sparse) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In MetacellsByGroups(seurat_obj, group.by = c("cell_type"), k = a[1],  :
  Removing the following groups that did not meet min_cells: Plasma cells

The above was after using 
a <- c(25, 2, 2). But the same error occurs when I tried multiple other parameters as well.

**Comment by smorabit** [comment] 2022-09-06 23:11
Hi, this is a duplicate of issue #46. I posted a potential solution so please try that out and please add any additional information to that thread.

**Closed as completed by smorabit** 2022-09-06 23:11 UTC

**Comment by magieer** [comment] 2024-12-12 15:34
When using the hdWGCNA package, if I did not apply the SCT method for normalization and instead used NormalizeData and ScaleData in my Seurat workflow, can I use scale.data directly as the input for constructing the co-expression network? Or is there a recommended slot (e.g., data or scale.data) that should be used for this analysis?
