### ISSUE TITLE
MetacellsByGroups function, I get an error 

### ISSUE THREAD

**Issue by cccccdoinb** [smorabit/scWGCNA#100] opened 2023-03-21 10:20 UTC
When I run the MetacellsByGroups function, I get an error and can't find a solution, how do I fix it?

> seurat_obj <- MetacellsByGroups(
+   seurat_obj = seurat_obj,
+   group.by = c("celltype", "stage"), # specify the columns in seurat_obj@meta.data to group by
+   k = 40, # nearest-neighbors parameter
+   reduction = "pca", 
+   slot='counts',
+   min_cells = 5,
+   max_shared = 10, # maximum number of shared cells between two metacells
+   ident.group = 'celltype',
+   mode = "average",# set the Idents of the metacell seurat object
+ )
Error in apply(cell_sample, 1, function(x) { : dim(X)的值必需是正数

**Comment by smorabit** [comment] 2023-03-21 16:35
Hard for me to tell what is going on without more information, but I am guessing that your `min_cells` is too low. Try making `min_cells` > `k`. 

Also, I am wondering if you can reproduce this error using the tutorial dataset?

**Comment by Montsecb** [comment] 2023-03-22 10:49
Hi, 
I get the same error, even if I set min_cells > k.  If the number of min_cells is greater than 100, it works. Here is my code: 

```
seurat_obj <- MetacellsByGroups(seurat_obj,
                                group.by = c("Subtypes"), # specify the columns in seurat_obj@meta.data to group by
                                reduction = 'pca', # select the dimensionality reduction to perform KNN on
                                k = 25, # nearest-neighbors parameter
                                min_cells = 70,
                                max_shared = 5, # maximum number of shared cells between two metacells
                                ident.group = 'Subtypes', # set the Idents of the metacell seurat object
                                assay="RNA", 
                                slot="counts")
```

**Comment by smorabit** [comment] 2023-03-23 16:25
Are you able to reproduce the error on the tutorial dataset or some other publicly available data?

**Comment by Montsecb** [comment] 2023-03-24 09:12
Hi,  I have followed the tutorial with the example dataset you provide and no errors appear with `k=25` and `min_cells=70`. Could it be due to the number of cells in my data? I was trying to create metacells with around 6k cells.

**Comment by smorabit** [comment] 2023-03-25 00:48
Hmm I am not sure what could be causing your issue at this time since I am not able to reproduce it. I will need to be able to reproduce the error in order to help resolve it.

**Comment by smorabit** [comment] 2023-04-03 16:16
Closing for now but happy to look into this if a reproducible example is provided.

**Closed as completed by smorabit** 2023-04-03 16:16 UTC

**Comment by mmzielonka** [comment] 2024-04-18 10:27
Hi @Montsecb and @cccccdoinb , did you ever resolve this issue? I am encountering the same error in my dataset. thank you!

**Comment by bpyenson** [comment] 2024-06-23 17:18
Hi, I'd like to re-open this issue to suggest a workaround I found by lowering the value of k:

This provides an error:
brainonly_2 <- MetacellsByGroups(
  seurat_obj = brainonly_2,
  group.by = c("celltype_brainonly2", "orig.ident"), # specify the columns in seurat_obj@meta.data to group by
  ###accounting
  reduction = 'pca', # selecting the dimensionality reduction I used to cluster my data
  k = 25, # nearest-neighbors parameter, 20 works whereas
  max_shared = 0, # maximum number of shared cells between two metacells
  ident.group = 'celltype_brainonly2', # set the Idents of the metacell seurat object
  slot= 'counts', #could use data for log-normalized, but only want counts, but of those ~14K genes used in analysis
  assay= 'SCT' #still specify that this is SCT assay
)

Error in apply(cell_sample, 1, function(x) { : 
  dim(X) must have a positive length
In addition: Warning message:
In MetacellsByGroups(seurat_obj = brainonly_2, group.by = c("celltype_brainonly2",  :
  Removing the following groups that did not meet min_cells: AG#ded2, CG#ded1, CG#ded2, CG#ded3, CG#mom1, CG#mom2, CG#mom3, EG#mom2, PR#ded1, PR#ded2, PR#ded3, PR#mom1, PR#mom2, PR#mom3


Whereas, the error is eliminated with my dataset when I lower k from 25 to 20:

brainonly_2 <- MetacellsByGroups(
  seurat_obj = brainonly_2,
  group.by = c("celltype_brainonly2", "orig.ident"), # specify the columns in seurat_obj@meta.data to group by
  ###accounting
  reduction = 'pca', # selecting the dimensionality reduction I used to cluster my data
  k = 20, # nearest-neighbors parameter, 20 works whereas
  max_shared = 0, # maximum number of shared cells between two metacells
  ident.group = 'celltype_brainonly2', # set the Idents of the metacell seurat object
  slot= 'counts', #could use data for log-normalized, but only want counts, but of those ~14K genes used in analysis
  assay= 'SCT' #still specify that this is SCT assay
)

Warning message:
In MetacellsByGroups(seurat_obj = brainonly_2, group.by = c("celltype_brainonly2",  :
  Removing the following groups that did not meet min_cells: AG#ded2, CG#ded1, CG#ded2, CG#ded3, CG#mom1, CG#mom2, CG#mom3, EG#mom2, PR#ded1, PR#ded2, PR#ded3, PR#mom1, PR#mom2, PR#mom3
