### ISSUE TITLE
Error in irlba(A = t(x = object), nv = npcs, ...) : max(nu, nv) must be positive

### ISSUE THREAD

**Issue by ps120195** [smorabit/scWGCNA#15] opened 2022-05-19 04:48 UTC
Hello,
I was going through this hdWGCNA pipeline by using the trial data of its own. I am getting this error in the following step in metacell seurat object processing 

> seurat_obj <- seurat_obj %>%
  NormalizeMetacells() %>%
  ScaleMetacells(features=VariableFeatures(seurat_obj)) %>%
  RunPCAMetacells(features=VariableFeatures(seurat_obj)) %>%
  RunHarmonyMetacells(group.by.vars='Sample') %>%
  RunUMAPMetacells(reduction='harmony', dims=1:15)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |======================================================================| 100%
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive

**Comment by smorabit** [comment] 2022-05-24 23:55
Closing this since this is a repeat of #9. Feel free to re-open that issue but I was not able to replicate this issue on my side so please provide more information.

**Closed as completed by smorabit** 2022-05-24 23:55 UTC

**Comment by huxiaoti** [comment] 2022-10-08 22:36
This error may be caused by the VariableFeatures of seurat_obj  is NuLL
Try to use `seurat_obj = FindVariableFeatures(seurat_obj)` to solve this error.

**Comment by yqzhao123** [comment] 2023-12-04 07:58
Please tell me which step to join before ?
