### ISSUE TITLE
Error running `ConstructNetwork()`

### ISSUE THREAD

**Issue by jhb1980** [smorabit/scWGCNA#274] opened 2024-06-05 12:16 UTC
Hi,

I'm very much looking forward to digging into my data using your package. I'm following the steps outlined in the basic tutorial using an own Seurat (V5) object, but ran into the following error (skipping function output up to consensus module merging):

```
s <- ConstructNetwork(s,
     tom_name = "test", 
     networkType = "unsigned", 
     TOMType = "unsigned", 
     overwrite_tom = TRUE, 
     tom_outdir = "test/TOM")

..merging consensus modules that are too close..
Error in SetModules(seurat_obj, mod_df = data.frame(gene_name = names(mods),  : 
  unused argument (mod_df = data.frame(gene_name = names(mods), module = factor(mods, levels = unique(mods)), color = mods))
```

**Comment by smorabit** [comment] 2024-06-05 12:18
Duplicate of issue #267, please look for the solution there and remember to use the search feature in the future.

**Closed as completed by smorabit** 2024-06-05 12:18 UTC
